services:
  backend:
    build: ./backend
    container_name: mern-backend
    restart: always
    env_file:
      - ./backend/.env
    expose:
      - "3001"
    networks:
      - mern-net

  client:
    build: ./client
    container_name: mern-client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mern-net

networks:
  mern-net:
    driver: bridge
